language: node_js

node_js:  
  - "lts/*"

sudo: required

services:
  - docker

env:
  global:
    - PORT=3000
    - DB_HOSTNAME=mongo
  matrix:
    # Any separate test environment variables go here, one per line each creating a different test environment

script:
  - docker-compose up --exit-code-from test test

cache:
  npm: true