# Unit testing dockerfile (for CI/CD)
# Use node 8-LTS
FROM node:8

RUN mkdir -p /usr/src/nijobs-be
WORKDIR /usr/src/nijobs-be

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# Install Node Packages (only production if not in dev mode)
RUN npm install

# Copying app source
COPY ./src ./src

# Copying test suite
COPY ./test ./test

EXPOSE $PORT
CMD ["npm", "test"]