# Production deployment dockerfile
FROM node:14.13.1

WORKDIR /usr/src/app

# Install app dependencies
COPY package.json package-lock.json ./

# Install Node Packages (only production)
RUN npm install --production

# Copying app source
COPY src/ src/

# Copying .env files
COPY .env* ./

# Copying babel config
COPY babel.config.json ./

CMD ["npm", "run", "prod"]
