version: "3"
services:
  web-prod:
    build: 
      context: .
      dockerfile: Dockerfile-prod
    volumes:
      - ./src:/usr/src/nijobs-be/src
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - NODE_ENV=prod
      - DB_HOSTNAME=mongo
    depends_on:
      - mongo
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - NODE_ENV=dev
      - DB_HOSTNAME=mongo
    volumes:
      - ./src:/usr/src/nijobs-be/src
    depends_on:
      - mongo
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - NODE_ENV=test
      - DB_HOSTNAME=mongo
    volumes:
      - ./src:/usr/src/nijobs-be/src
      - ./test:/usr/src/nijobs-be/test
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"