version: "3"
services:
  web-prod:
    build: 
      context: .
      dockerfile: Dockerfile-prod
    environment:
      - DB_HOST=mongo
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DB_HOST=mongo
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - mongo
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    environment:
      - DB_HOST=mongo
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
      - ./coverage:/usr/src/app/coverage
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
