# Production deployment dockerfile
FROM node:12.18.4

WORKDIR /usr/src/app

# Install app dependencies
COPY package.json package-lock.json ./

# Install Node Packages (only production)
RUN npm install --production

# Copying app source
COPY src/ src/

# Copying .env files
COPY .env* ./

CMD ["npm", "run", "prod"]
