export const TechnologyTypes = Object.freeze([
    ".NET",
    ".NET Core",
    ".NET Entity Framework",
    "Abap",
    "Ada",
    "Alpine",
    "Android",
    "Angular",
    "Ansible",
    "Apache",
    "Apollo",
    "Appium",
    "ASP.NET",
    "ASP.NET Core",
    "Aurelia",
    "AWS",
    "Azure",
    "Beego",
    "Browserstack",
    "C",
    "C#",
    "C++",
    "Cassandra",
    "CircleCI",
    "Clojure",
    "Cobol",
    "CodeIgniter",
    "CouchDB",
    "CSS",
    "Cypress",
    "D",
    "Dart",
    "DevOps",
    "Django",
    "Docker",
    "Drupal",
    "Elasticsearch",
    "Electron",
    "Elixir",
    "EmberJS",
    "Erlang",
    "ExpressJS",
    "F#",
    "FastAPI",
    "Flask",
    "Flutter",
    "Fortran",
    "Gatsby",
    "Git",
    "Go",
    "Google Cloud",
    "Grafana",
    "Graphite",
    "GraphQL",
    "Groovy",
    "GTK+",
    "H2",
    "Hadoop",
    "Haskell",
    "HTML",
    "IBM DB2",
    "iOS",
    "Iris",
    "Java",
    "JavaScript",
    "Jenkins",
    "Jest",
    "Jira",
    "JQuery",
    "Julia",
    "Junit",
    "Keras",
    "Koa",
    "Kotlin",
    "Kubernetes",
    "Laravel",
    "Linux",
    "LitElement",
    "Lua",
    "MacOS",
    "MariaDB",
    "Matlab",
    "Meteor",
    "Mocha",
    "MongoDB",
    "MySQL",
    "NextJS",
    "Nginx",
    "NodeJS",
    "NoSQL",
    "Objective-C",
    "OpenAI",
    "OpenCL",
    "OpenCV",
    "OpenGL",
    "Oracle Database",
    "Pascal",
    "Perl",
    "Phoenix",
    "PHP",
    "PHPUnit",
    "Polymer",
    "PostgreSQL",
    "Preact",
    "Prolog",
    "Prometheus",
    "Pytest",
    "Python",
    "PyTorch",
    "Qt",
    "R",
    "RabbitMQ",
    "React",
    "React Native",
    "Redis",
    "Robot Framework",
    "Ruby",
    "Rust",
    "Scala",
    "Scheme",
    "Selenium",
    "Shell",
    "Spring",
    "Spring Boot",
    "SQL",
    "SQL Server",
    "Stimulus",
    "Strapi",
    "Svelte",
    "Swift",
    "Swing",
    "Symfony",
    "Tensorflow",
    "Terraform",
    "TypeScript",
    "Unity",
    "Unreal Engine",
    "VBA",
    "VirtualBox",
    "Visual Basic",
    "VMWare",
    "VueJS",
    "WebdriverIO",
    "Windows",
    "WordPress",
    "Xamarin",
    "Yii",
    "Other"
]);

export const MIN_TECHNOLOGIES = 1;
export const MAX_TECHNOLOGIES = 7;
