const MONTH_IN_MS = 1000 * 3600 * 24 * 30.42;
const HOUR_IN_MS = 1000 * 3600;
const OFFER_MAX_LIFETIME_MONTHS = 6;

// In hours
const OFFER_EDIT_GRACE_PERIOD = 1;
module.exports = {
    MONTH_IN_MS, OFFER_MAX_LIFETIME_MONTHS, HOUR_IN_MS, OFFER_EDIT_GRACE_PERIOD,
};
