const TechnologyTypes = Object.freeze([
    "Ada",
    "Android",
    "Angular",
    "Ansible",
    "Apache",
    "Apollo",
    "ASP .NET",
    "ASP .NET Core",
    "Aurelia",
    "AWS",
    "Azure",
    "Big Data",
    "Blockchain",
    "Cassandra",
    "C",
    "C#",
    "C++",
    "Clojure",
    "CouchDB",
    "CSS",
    "Dart",
    "D",
    "Deep Learning",
    "DevOps",
    "Django",
    "Docker",
    "Drupal",
    "Elasticsearch",
    "Electron",
    "Elixir",
    "EmberJS",
    "Erlang",
    "Express",
    "F#",
    "Flask",
    "Flutter",
    "Fortran",
    "Gatsby",
    "Go",
    "Google Cloud Platform",
    "Grafana",
    "Graphite",
    "GraphQL",
    "Groovy",
    "GTK+",
    "Hadoop",
    "Haskell",
    "HTML",
    "iOS",
    "Java",
    "Jira",
    "JavaScript",
    "jQuery",
    "Julia",
    "Keras",
    "Kotlin",
    "Kubernetes",
    "Laravel",
    "Linux",
    "macOS",
    "Meteor",
    "Mobile",
    "MongoDB",
    "MySQL",
    ".NET",
    ".NET Core",
    ".NET Entity Framework",
    "Next.js",
    "Nginx",
    "NodeJS",
    "NoSQL",
    "Objective-C",
    "OpenAI",
    "OpenCL",
    "OpenCV",
    "OpenGL",
    "Oracle Database",
    "Pascal",
    "Pascalzim",
    "Phoenix",
    "PHP",
    "Polymer",
    "PostgreSQL",
    "Prolog",
    "Prometheus",
    "Python",
    "PyTorch",
    "Qt",
    "Quality Assurance",
    "RabbitMQ",
    "React Native",
    "React",
    "Redis",
    "R",
    "Ruby",
    "Rust",
    "Scala",
    "Scheme",
    "Security",
    "Selenium",
    "Shell",
    "Spring Boot",
    "Spring",
    "SQL Server",
    "SQL",
    "Svelte",
    "Swift",
    "Swing",
    "Symfony",
    "Tensorflow",
    "Terraform",
    "TypeScript",
    "Unity",
    "Unreal Engine",
    "VirtualBox",
    "Visual Basic",
    "VMWare",
    "Vue.js",
    "Windows",
    "WordPress",
    "Xamarin",
]);

const MIN_TECHNOLOGIES = 1;
const MAX_TECHNOLOGIES = 7;

module.exports = {
    TechnologyTypes,
    MIN_TECHNOLOGIES,
    MAX_TECHNOLOGIES,
};
